version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:5.6.14"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    logging:
      driver: none
    ports:
      - 3050:80
  api:
    container_name: swift-server
    build:
      dockerfile: Dockerfile.dev
      context: ../swift-server
    volumes:
      - ../swift-server:/app
  client:
    container_name: swift-client
    build:
      dockerfile: Dockerfile.dev
      context: ../swift-client
    volumes:
      - ../swift-client:/app
