apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /pv/elasticsearch
  storageClassName: manual
